import Image from 'next/image'
import { clsx } from 'clsx/lite'
import type { ComponentProps } from 'react'
import { Section } from '../elements/section'

export type PhotoExample = {
  src: string
  alt: string
  caption?: string
}

export function SiloPhotoExample({
  src,
  alt,
  caption,
  className,
  ...props
}: PhotoExample & ComponentProps<'li'>) {
  return (
    <li className={clsx('flex flex-col gap-4 text-sm/7', className)} {...props}>
      <div className="aspect-3/4 w-full overflow-hidden rounded-sm outline -outline-offset-1 outline-black/5 dark:outline-white/5">
        <Image
          src={src}
          alt={alt}
          width={800}
          height={1067}
          className="size-full object-cover"
        />
      </div>
      {caption && (
        <p className="text-mist-700 dark:text-mist-400">{caption}</p>
      )}
    </li>
  )
}

export function SiloPhotoExamples({
  industry,
  examples,
  className,
  ...props
}: {
  industry: string
  examples: PhotoExample[]
} & Omit<ComponentProps<typeof Section>, 'children'>) {
  return (
    <Section
      eyebrow={
        <span className="bg-gradient-to-r from-orange-500 to-rose-500 bg-clip-text font-semibold text-transparent">
          AI-generated. Indistinguishable from studio.
        </span>
      }
      headline={`${industry} Product Photography Examples`}
      subheadline={
        <p>
          Real product photos generated by Yuzuu for {industry.toLowerCase()} brands. No studio, no photographer, no waiting.
        </p>
      }
      className={className}
      {...props}
    >
      <ul role="list" className="grid grid-cols-1 gap-x-2 gap-y-10 sm:grid-cols-2 md:grid-cols-3">
        {examples.map((example, i) => (
          <SiloPhotoExample key={i} {...example} />
        ))}
      </ul>
    </Section>
  )
}
